/**
 * NEST — Phase 4
 * data.js — Product Catalogue
 * 52 products across 7 categories
 * Ultra-High-Quality Audited Product Image Catalogue
 */

const CATEGORIES = [
  'Smart Speakers & Audio',
  'Smart Lighting',
  'Security Devices',
  'Climate & Appliances',
  'Connectivity & Power',
  'Kitchen Essentials',
  'Cleaning Devices',
];

const PRODUCTS = [

  /* ─────────────────────────────────────────────────────
     SMART SPEAKERS & AUDIO  (8 products)
  ───────────────────────────────────────────────────── */
  {
    id:          'nest-sound-studio',
    name:        'Nest Sound Studio',
    category:    'Smart Speakers & Audio',
    description: 'Room-filling audio with adaptive intelligence and pristine clarity. Bi-amplified drivers, 360° sound.',
    price:       24999,
    rating:      4.8,
    image:       'https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=2000&auto=format&fit=crop',
    popularity:  98,
    featured:    true,
    newArrival:  false,
  },
  {
    id:          'nest-audio-mini',
    name:        'Nest Audio Mini',
    category:    'Smart Speakers & Audio',
    description: 'Compact smart speaker with surprisingly powerful sound. Perfect for any room.',
    price:       7999,
    rating:      4.5,
    image:       'https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=2000&auto=format&fit=crop',
    popularity:  85,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-bass-pro',
    name:        'Nest Bass Pro',
    category:    'Smart Speakers & Audio',
    description: 'Floor-standing smart speaker with deep, rich bass and studio-grade separation.',
    price:       34999,
    rating:      4.9,
    image:       'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=2000&auto=format&fit=crop',
    popularity:  92,
    featured:    true,
    newArrival:  false,
  },
  {
    id:          'nest-stereo-pair',
    name:        'Nest Stereo Pair',
    category:    'Smart Speakers & Audio',
    description: 'Two matched speakers wirelessly bonded for true stereo separation and audiophile staging.',
    price:       44999,
    rating:      4.7,
    image:       'https://images.unsplash.com/photo-1589003077984-894e133dabab?q=80&w=2000&auto=format&fit=crop',
    popularity:  78,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-portable-play',
    name:        'Nest Portable Play',
    category:    'Smart Speakers & Audio',
    description: 'IP67 waterproof portable speaker. 18-hour battery, outdoor-ready, indoor-quality sound.',
    price:       12999,
    rating:      4.3,
    image:       'https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=2000&auto=format&fit=crop',
    popularity:  80,
    featured:    false,
    newArrival:  true,
  },
  {
    id:          'nest-cinema-soundbar',
    name:        'Nest Cinema Soundbar',
    category:    'Smart Speakers & Audio',
    description: 'Dolby Atmos soundbar with dedicated height drivers. Transforms any TV into a cinema.',
    price:       54999,
    rating:      4.6,
    image:       'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=2000&auto=format&fit=crop',
    popularity:  70,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-bookshelf-s1',
    name:        'Nest Bookshelf S1',
    category:    'Smart Speakers & Audio',
    description: 'Studio-tuned bookshelf speakers with wireless streaming and high-resolution audio.',
    price:       18999,
    rating:      4.4,
    image:       'https://images.unsplash.com/photo-1491927570842-0261e477d937?q=80&w=2000&auto=format&fit=crop',
    popularity:  65,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-pocket-speaker',
    name:        'Nest Pocket Speaker',
    category:    'Smart Speakers & Audio',
    description: 'Ultra-compact pocket speaker. Fits anywhere, sounds larger than it looks.',
    price:       3999,
    rating:      4.1,
    image:       'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?q=80&w=2000&auto=format&fit=crop',
    popularity:  60,
    featured:    false,
    newArrival:  true,
  },

  /* ─────────────────────────────────────────────────────
     SMART LIGHTING  (7 products)
  ───────────────────────────────────────────────────── */
  {
    id:          'nest-glow-ambient',
    name:        'Nest Glow Ambient',
    category:    'Smart Lighting',
    description: 'Architectural light that responds to your mood and time of day. 16 million colours.',
    price:       14999,
    rating:      4.7,
    image:       'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=1600&auto=format&fit=crop',
    popularity:  90,
    featured:    true,
    newArrival:  true,
  },
  {
    id:          'nest-strip-light-pro',
    name:        'Nest Strip Light Pro',
    category:    'Smart Lighting',
    description: '5-metre RGBWW LED strip with music sync, scene presets, and Matter compatibility.',
    price:       6499,
    rating:      4.4,
    image:       'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?q=80&w=1600&auto=format&fit=crop',
    popularity:  82,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-ceiling-smart',
    name:        'Nest Ceiling Smart',
    category:    'Smart Lighting',
    description: 'Flush-mount smart ceiling light with adaptive colour temperature and motion sensor.',
    price:       21999,
    rating:      4.6,
    image:       'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?q=80&w=1600&auto=format&fit=crop',
    popularity:  74,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-desk-lamp-s1',
    name:        'Nest Desk Lamp S1',
    category:    'Smart Lighting',
    description: 'Precision-crafted desk lamp with wireless charging base and tunable white light.',
    price:       8999,
    rating:      4.3,
    image:       'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1600&auto=format&fit=crop',
    popularity:  68,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-bulb-starter-pack',
    name:        'Nest Bulb Starter Pack',
    category:    'Smart Lighting',
    description: 'Four smart bulbs, one hub, unlimited possibilities. The easiest way to start.',
    price:       4499,
    rating:      4.2,
    image:       'https://images.unsplash.com/photo-1517991104123-1d56a6e81ed9?q=80&w=1600&auto=format&fit=crop',
    popularity:  88,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-outdoor-light',
    name:        'Nest Outdoor Light',
    category:    'Smart Lighting',
    description: 'Weather-resistant smart outdoor light with dusk-to-dawn scheduling and motion alerts.',
    price:       11999,
    rating:      4.5,
    image:       'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=1600&auto=format&fit=crop',
    popularity:  72,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-floor-lamp-arc',
    name:        'Nest Floor Lamp Arc',
    category:    'Smart Lighting',
    description: 'Statement arc floor lamp with voice control and a warm, sculpted aluminium finish.',
    price:       28999,
    rating:      4.6,
    image:       'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?q=80&w=1600&auto=format&fit=crop',
    popularity:  55,
    featured:    false,
    newArrival:  false,
  },

  /* ─────────────────────────────────────────────────────
     SECURITY DEVICES  (8 products)
  ───────────────────────────────────────────────────── */
  {
    id:          'nest-vision-pro',
    name:        'Nest Vision Pro',
    category:    'Security Devices',
    description: '4K HDR camera with night vision, intelligent motion detection, and two-way audio.',
    price:       20799,
    rating:      4.8,
    image:       'https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?q=80&w=2000&auto=format&fit=crop',
    popularity:  95,
    featured:    true,
    newArrival:  false,
  },
  {
    id:          'nest-doorbell-hd',
    name:        'Nest Doorbell HD',
    category:    'Security Devices',
    description: 'Wired HD video doorbell with face recognition, package detection, and live view.',
    price:       12999,
    rating:      4.5,
    image:       'https://images.unsplash.com/photo-1563013544-824ae1b704d3?q=80&w=2000&auto=format&fit=crop',
    popularity:  86,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-smart-lock-elite',
    name:        'Nest Smart Lock Elite',
    category:    'Security Devices',
    description: 'Fingerprint, PIN, and app-controlled smart lock. Auto-locks, guest access, tamper alerts.',
    price:       25999,
    rating:      4.9,
    image:       'https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=2000&auto=format&fit=crop',
    popularity:  93,
    featured:    true,
    newArrival:  false,
  },
  {
    id:          'nest-cam-outdoor',
    name:        'Nest Cam Outdoor',
    category:    'Security Devices',
    description: 'Weatherproof outdoor camera with colour night vision, activity zones, and 24/7 recording.',
    price:       15999,
    rating:      4.6,
    image:       'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2000&auto=format&fit=crop',
    popularity:  80,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-motion-sensor',
    name:        'Nest Motion Sensor',
    category:    'Security Devices',
    description: 'Slim passive infrared sensor. Works with all Nest devices to trigger automations.',
    price:       3499,
    rating:      4.3,
    image:       'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=2000&auto=format&fit=crop',
    popularity:  70,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-security-hub',
    name:        'Nest Security Hub',
    category:    'Security Devices',
    description: 'Central command for your entire Nest security ecosystem. Built-in siren, battery backup.',
    price:       34999,
    rating:      4.7,
    image:       'https://images.unsplash.com/photo-1516321165247-4aa89a48be28?q=80&w=2000&auto=format&fit=crop',
    popularity:  62,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-glass-break-sensor',
    name:        'Nest Glass Break Sensor',
    category:    'Security Devices',
    description: 'AI-powered acoustic sensor detects glass breaking in a 9-metre radius instantly.',
    price:       4999,
    rating:      4.2,
    image:       'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=2000&auto=format&fit=crop',
    popularity:  55,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-floodlight-cam',
    name:        'Nest Floodlight Cam',
    category:    'Security Devices',
    description: '2000-lumen smart floodlight with integrated 1080p camera and person detection.',
    price:       22999,
    rating:      4.5,
    image:       'https://images.unsplash.com/photo-1496171367470-9ed9a91ea931?q=80&w=2000&auto=format&fit=crop',
    popularity:  68,
    featured:    false,
    newArrival:  true,
  },

  /* ─────────────────────────────────────────────────────
     CLIMATE & APPLIANCES  (7 products)
  ───────────────────────────────────────────────────── */
  {
    id:          'nest-climate-pro',
    name:        'Nest Climate Pro',
    category:    'Climate & Appliances',
    description: 'Learning thermostat that adapts to your schedule, saves energy, and stays ahead of the weather.',
    price:       16699,
    rating:      4.7,
    image:       'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?q=80&w=1600&auto=format&fit=crop',
    popularity:  91,
    featured:    true,
    newArrival:  false,
  },
  {
    id:          'nest-air-purifier-elite',
    name:        'Nest Air Purifier Elite',
    category:    'Climate & Appliances',
    description: 'H13 HEPA + activated carbon purifier. Covers 60m², auto-adjusts to air quality readings.',
    price:       28999,
    rating:      4.8,
    image:       'https://images.unsplash.com/photo-1595861173950-4824c6d6c4d4?q=80&w=1600&auto=format&fit=crop',
    popularity:  84,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-smart-fan',
    name:        'Nest Smart Fan',
    category:    'Climate & Appliances',
    description: 'Silent DC motor ceiling fan with light kit, app control, and seasonal scheduling.',
    price:       9999,
    rating:      4.4,
    image:       'https://images.unsplash.com/photo-1494526585095-c41746248156?q=80&w=1600&auto=format&fit=crop',
    popularity:  72,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-humidifier-s1',
    name:        'Nest Humidifier S1',
    category:    'Climate & Appliances',
    description: 'Ultrasonic smart humidifier with auto humidity sensing and essential oil diffuser.',
    price:       7499,
    rating:      4.3,
    image:       'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1600&auto=format&fit=crop',
    popularity:  60,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-thermo-display',
    name:        'Nest Thermo Display',
    category:    'Climate & Appliances',
    description: 'Elegant 5-inch ambient display for smart thermostat. Shows temperature, time, and energy use.',
    price:       12999,
    rating:      4.6,
    image:       'https://images.unsplash.com/photo-1484154218962-a197022b5858?q=80&w=1600&auto=format&fit=crop',
    popularity:  65,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-air-monitor',
    name:        'Nest Air Monitor',
    category:    'Climate & Appliances',
    description: 'Tracks CO₂, VOCs, PM2.5, humidity, and temperature. Beautiful ambient air quality display.',
    price:       6999,
    rating:      4.5,
    image:       'https://images.unsplash.com/photo-1460317442991-0ec209397118?q=80&w=1600&auto=format&fit=crop',
    popularity:  77,
    featured:    false,
    newArrival:  true,
  },
  {
    id:          'nest-smart-heater',
    name:        'Nest Smart Heater',
    category:    'Climate & Appliances',
    description: 'Ceramic smart heater with rapid warmth, over-heat protection, and geo-fencing support.',
    price:       19999,
    rating:      4.4,
    image:       'https://images.unsplash.com/photo-1507668077129-56e32842fceb?q=80&w=1600&auto=format&fit=crop',
    popularity:  58,
    featured:    false,
    newArrival:  false,
  },

  /* ─────────────────────────────────────────────────────
     CONNECTIVITY & POWER  (7 products)
  ───────────────────────────────────────────────────── */
  {
    id:          'nest-router-pro',
    name:        'Nest Router Pro',
    category:    'Connectivity & Power',
    description: 'Wi-Fi 6E tri-band router with NEST ecosystem priority lane and parental controls.',
    price:       19999,
    rating:      4.7,
    image:       'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?q=80&w=1600&auto=format&fit=crop',
    popularity:  88,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-smart-plug-4pack',
    name:        'Nest Smart Plug 4-Pack',
    category:    'Connectivity & Power',
    description: 'Matter-compatible smart plugs with energy monitoring, timer, and away mode.',
    price:       3999,
    rating:      4.5,
    image:       'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=1600&auto=format&fit=crop',
    popularity:  92,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-power-strip-elite',
    name:        'Nest Power Strip Elite',
    category:    'Connectivity & Power',
    description: '6-outlet smart power strip with individual control, surge protection, and USB-C PD port.',
    price:       8499,
    rating:      4.6,
    image:       'https://images.unsplash.com/photo-1520869562399-e772f042f422?q=80&w=1600&auto=format&fit=crop',
    popularity:  79,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-range-extender',
    name:        'Nest Range Extender',
    category:    'Connectivity & Power',
    description: 'Mesh Wi-Fi satellite node. Extends coverage up to 185m² with zero dead zones.',
    price:       5999,
    rating:      4.3,
    image:       'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1600&auto=format&fit=crop',
    popularity:  70,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-usb-hub-pro',
    name:        'Nest USB Hub Pro',
    category:    'Connectivity & Power',
    description: '10-in-1 smart USB-C hub with Ethernet, 4K HDMI, 100W passthrough, and SD reader.',
    price:       6999,
    rating:      4.4,
    image:       'https://images.unsplash.com/photo-1516321497487-e288fb19713f?q=80&w=1600&auto=format&fit=crop',
    popularity:  74,
    featured:    false,
    newArrival:  true,
  },
  {
    id:          'nest-wireless-charger',
    name:        'Nest Wireless Charger',
    category:    'Connectivity & Power',
    description: '3-in-1 Qi2 charging pad for phone, earbuds, and watch. 15W fast wireless charging.',
    price:       4499,
    rating:      4.2,
    image:       'https://images.unsplash.com/photo-1496171367470-9ed9a91ea931?q=80&w=1600&auto=format&fit=crop',
    popularity:  66,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-mesh-node',
    name:        'Nest Mesh Node',
    category:    'Connectivity & Power',
    description: 'Tri-band mesh satellite seamlessly extends NEST Router Pro to every corner of your home.',
    price:       14999,
    rating:      4.6,
    image:       'https://images.unsplash.com/photo-1527443154391-507e9dc6c5cc?q=80&w=1600&auto=format&fit=crop',
    popularity:  80,
    featured:    false,
    newArrival:  false,
  },

  /* ─────────────────────────────────────────────────────
     KITCHEN ESSENTIALS  (7 products)
  ───────────────────────────────────────────────────── */
  {
    id:          'nest-coffee-station',
    name:        'Nest Coffee Station',
    category:    'Kitchen Essentials',
    description: 'Fully automated bean-to-cup coffee machine. Scheduled brew, voice control, 12 drink modes.',
    price:       34999,
    rating:      4.7,
    image:       'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=2000&auto=format&fit=crop',
    popularity:  85,
    featured:    true,
    newArrival:  false,
  },
  {
    id:          'nest-kettle-smart',
    name:        'Nest Kettle Smart',
    category:    'Kitchen Essentials',
    description: 'Variable temperature smart kettle with app control, keep-warm mode, and steel finish.',
    price:       8999,
    rating:      4.5,
    image:       'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?q=80&w=2000&auto=format&fit=crop',
    popularity:  80,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-smart-scale',
    name:        'Nest Smart Scale',
    category:    'Kitchen Essentials',
    description: 'Precision kitchen scale with recipe guidance, nutritional tracking, and app pairing.',
    price:       5499,
    rating:      4.3,
    image:       'https://images.unsplash.com/photo-1588776814546-daab30f310ce?q=80&w=2000&auto=format&fit=crop',
    popularity:  65,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-blender-pro',
    name:        'Nest Blender Pro',
    category:    'Kitchen Essentials',
    description: '2200W smart blender with noise-dampening lid, self-cleaning mode, and preset programmes.',
    price:       22999,
    rating:      4.6,
    image:       'https://images.unsplash.com/photo-1570222094114-d054a817e56b?q=80&w=2000&auto=format&fit=crop',
    popularity:  70,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-toaster-elite',
    name:        'Nest Toaster Elite',
    category:    'Kitchen Essentials',
    description: 'Smart toaster with 12 browning settings, countdown display, and timed wake-up mode.',
    price:       11999,
    rating:      4.4,
    image:       'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?q=80&w=2000&auto=format&fit=crop',
    popularity:  60,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-sous-vide-pod',
    name:        'Nest Sous Vide Pro',
    category:    'Kitchen Essentials',
    description: 'Precision immersion circulator with 0.1°C accuracy, quiet motor, and guided recipe app.',
    price:       16999,
    rating:      4.5,
    image:       'https://images.unsplash.com/photo-1547592180-85f173990554?q=80&w=2000&auto=format&fit=crop',
    popularity:  55,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-display-cooker',
    name:        'Nest Display Cooker',
    category:    'Kitchen Essentials',
    description: 'Smart multicooker with 14-in-1 modes, built-in AI nutrition coach, and 6L capacity.',
    price:       44999,
    rating:      4.8,
    image:       'https://images.unsplash.com/photo-1586208958839-06c17cacdf08?q=80&w=2000&auto=format&fit=crop',
    popularity:  73,
    featured:    false,
    newArrival:  true,
  },

  /* ─────────────────────────────────────────────────────
     CLEANING DEVICES  (8 products)
  ───────────────────────────────────────────────────── */
  {
    id:          'nest-robo-vacuum-pro',
    name:        'Nest Robo Vacuum Pro',
    category:    'Cleaning Devices',
    description: 'Laser-mapped robot vacuum with AI obstacle avoidance, 4500Pa suction, and auto-empty base.',
    price:       39999,
    rating:      4.9,
    image:       'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=1600&auto=format&fit=crop',
    popularity:  97,
    featured:    true,
    newArrival:  false,
  },
  {
    id:          'nest-mop-bot',
    name:        'Nest Mop Bot',
    category:    'Cleaning Devices',
    description: 'Robotic mop with intelligent water management, carpet detection, and auto-lift technology.',
    price:       24999,
    rating:      4.7,
    image:       'https://images.unsplash.com/photo-1563453392212-326f5e854473?q=80&w=1600&auto=format&fit=crop',
    popularity:  83,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-handheld-vac',
    name:        'Nest Handheld Vac',
    category:    'Cleaning Devices',
    description: 'Cordless handheld vacuum with 85AW suction, flex-crevice tool, and 40-minute runtime.',
    price:       8999,
    rating:      4.4,
    image:       'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?q=80&w=1600&auto=format&fit=crop',
    popularity:  76,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-window-cleaner',
    name:        'Nest Window Cleaner',
    category:    'Cleaning Devices',
    description: 'Smart robotic window cleaner with AI path planning and anti-fall safety cable.',
    price:       14999,
    rating:      4.5,
    image:       'https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=1600&auto=format&fit=crop',
    popularity:  64,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-air-duster',
    name:        'Nest Air Duster',
    category:    'Cleaning Devices',
    description: 'Electric cordless air duster. Replaces canned air forever. 50000 RPM brushless motor.',
    price:       4999,
    rating:      4.2,
    image:       'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?q=80&w=1600&auto=format&fit=crop',
    popularity:  58,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-robo-combo',
    name:        'Nest Robo Combo',
    category:    'Cleaning Devices',
    description: 'Combined vacuum + mop robot with 6000Pa suction, hot-water mopping, and self-cleaning dock.',
    price:       54999,
    rating:      4.8,
    image:       'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=1600&auto=format&fit=crop',
    popularity:  89,
    featured:    true,
    newArrival:  false,
  },
  {
    id:          'nest-carpet-cleaner',
    name:        'Nest Carpet Cleaner',
    category:    'Cleaning Devices',
    description: 'Deep-clean smart carpet washer with heated water, 3-brush roll, and fast-dry technology.',
    price:       19999,
    rating:      4.6,
    image:       'https://images.unsplash.com/photo-1517142089942-ba376ce32a2e?q=80&w=1600&auto=format&fit=crop',
    popularity:  67,
    featured:    false,
    newArrival:  false,
  },
  {
    id:          'nest-pool-cleaner',
    name:        'Nest Pool Cleaner',
    category:    'Cleaning Devices',
    description: 'Autonomous robotic pool cleaner with wall-climbing, waterline scrubbing, and app scheduling.',
    price:       29999,
    rating:      4.5,
    image:       'https://images.unsplash.com/photo-1558618047-f05fa49f66d0?q=80&w=1600&auto=format&fit=crop',
    popularity:  52,
    featured:    false,
    newArrival:  false,
  },

];

/* Expose data globally for cart.js and product-detail.js */
window.CATEGORIES = CATEGORIES;
window.PRODUCTS = PRODUCTS;
